/**
    File containing helpers functions and constant variables
**/


import * as c3 from 'c3';
import $ from "jquery";
import * as d3 from 'd3';
import Chart from 'chart.js';


/*****************************************Constants initialization**************************************************/
// Window's resizing variables
const divs = ['#svg_male', '#svg_female', '.section_chart', '.timeseries_chart', '#level_chart', '#map', '.slider', '#back-button svg', '#forward-button svg'];
const ratios = [60.0 / 762, 60.0 / 762, 240.0 / 762, 240.0 / 762, 65.0 / 762, 270.0 / 762, 5.0 / 762, 18.0 / 762, 18.0 / 762];


//  maps between citizenship denominations and countries names 
export const citizenships_countries = {
    "Fijian": "Fiji",
    "New Zealander": "New Zealand",
    "Papua New Guinean": "Papua New Guinea",
    "Ni-Vanuatu": "Vanuatu",
    "New Caledonian": "France",
    "Australian": "Australia",
    "Solomon Islander": "Solomon Islands",
    "Bulgarian": "Bulgaria",
    "Belgian": "Belgium",
    "Byelorussian": "Belarus",
    "Bosnian": "Bosnia and Herzegovina",
    "Albanian": "Albania",
    "Austrian": "Austria",
    "Swiss": "Switzerland",
    "Czech": "Czech Republic",
    "German": "Germany",
    "French": "France",
    "Spanish": "Spain",
    "Finnish": "Finland",
    "Danish": "Denmark",
    "Estonian": "Estonia",
    "British": "United Kingdom",
    "Croatian": "Croatia",
    "Irish": "Ireland",
    "Hungarian": "Hungary",
    "Greek": "Greece",
    "Italian": "Italy",
    "Icelandic": "Iceland",
    "Kosovar": "Kosovo",
    "Luxembourgish": "Luxembourg",
    "Lithuanian": "Lithuania",
    "Moldovan": "Moldova",
    "Latvian": "Latvia",
    "Montenegrin": "Montenegro",
    "Macedonian": "Macedonia",
    "Dutch": "Netherlands",
    "Polish": "Poland",
    "Romanian": "Romania",
    "Portuguese": "Portugal",
    "Norwegian": "Norway",
    "Angolan": "Angola",
    "Beninese": "Benin",
    "Russian": "Russia",
    "Burundian": "Burundi",
    "Serbian": "Republic of Serbia",
    "Slovenian": "Slovenia",
    "Slovak": "Slovakia",
    "Burkinabe": "Burkina Faso",
    "Motswana": "Botswana",
    "Central African": "Central African Republic",
    "Ivorian": "Ivory Coast",
    "Cameroonian": "Cameroon",
    "Congolese": "Republic of Congo",
    "Djiboutian": "Djibouti",
    "Algerian": "Algeria",
    "Egyptian": "Egypt",
    "Eritrean": "Eritrea",
    "Ghanaian": "Ghana",
    "Gabonese": "Gabon",
    "Gambian": "Gambia",
    "Guinean": "Guinea Bissau",
    "Ethiopian": "Ethiopia",
    "Equatorial Guinean": "Equatorial Guinea",
    "Kenyan": "Kenya",
    "Swedish": "Sweden",
    "Liberian": "Liberia",
    "Libyan": "Libya",
    "Mosotho": "Lesotho",
    "Moroccan": "Morocco",
    "Malian": "Mali",
    "Mozambican": "Mozambique",
    "Malagasy": "Madagascar",
    "Mauritanian": "Mauritania",
    "Malawian": "Malawi",
    "Nigerian": "Nigeria",
    "Nigerien": "Niger",
    "Namibian": "Namibia",
    "Rwandan": "Rwanda",
    "Samoan": "Samoa",
    "Sudanese": "South Sudan",
    "Senegalese": "Senegal",
    "Ukrainian": "Ukraine",
    "Sierra Leonean": "Somaliland",
    "Somalian": "Somalia",
    "Swazi": "Swaziland",
    "Chadian": "Chad",
    "Tunisian": "Tunisia",
    "Tanzanian": "United Republic of Tanzania",
    "Togolese": "Togo",
    "Afghan": "Afghanistan",
    "Zimbabwean": "Zimbabwe",
    "Zambian": "Zambia",
    "South African": "South Africa",
    "Azerbaijani": "Azerbaijan",
    "Ugandan": "Uganda",
    "Armenian": "Armenia",
    "Bangladeshi": "Bangladesh",
    "Bhutanese": "Bhutan",
    "Chinese": "China",
    "Cypriot": "Cyprus",
    "Emirian": "United Arab Emirates",
    "Georgian": "Georgia",
    "Bruneian": "Brunei",
    "Indonesian": "Indonesia",
    "Indian": "India",
    "Israeli": "Israel",
    "Iranian": "Iran",
    "Iraqi": "Iraq",
    "Japanese": "Japan",
    "Jordanian": "Jordan",
    "Kazakh": "Kazakhstan",
    "Cambodian": "Cambodia",
    "Kuwaiti": "Kuwait",
    "Kirghiz": "Kyrgyzstan",
    "Laotian": "Laos",
    "Lebanese": "Lebanon",
    "Sri Lankan": "Sri Lanka",
    "South Korean": "South Korea",
    "Mongolian": "Mongolia",
    "Pakistani": "Pakistan",
    "Omani": "Oman",
    "Myanmarese": "Myanmar",
    "Nepali": "Nepal",
    "Malaysian": "Malaysia",
    "Filipino": "Philippines",
    "North Korean": "North Korea",
    "Qatari": "Qatar",
    "Saudi Arabian": "Saudi Arabia",
    "Tajik": "Tajikistan",
    "Syrian": "Syria",
    "Thai": "Thailand",
    "Turkish": "Turkey",
    "Turkmen": "Turkmenistan",
    "Taiwanese": "Taiwan",
    "East Timorian": "East Timor",
    "Uzbek": "Uzbekistan",
    "Vietnamese": "Vietnam",
    "Yemeni": "Yemen",
    "Argentinian": "Argentina",
    "Bolivian": "Bolivia",
    "Brazilian": "Brazil",
    "Ecuadorian": "Ecuador",
    "Chilean": "Chile",
    "Falkland Islander": "United Kingdom",
    "Colombian": "Colombia",
    "Guyanese": "Guyana",
    "Surinamer": "Suriname",
    "Peruvian": "Peru",
    "Paraguayan": "Paraguay",
    "Uruguayan": "Uruguay",
    "Venezuelan": "Venezuela",
    "Belizean": "Belize",
    "Canadian": "Canada",
    "Costa Rican": "Costa Rica",
    "Cuban": "Cuba",
    "Bahameese": "The Bahamas",
    "Dominican": "Dominican Republic",
    "Guatemalan": "Guatemala",
    "Greenlander": "Groenland",
    "Honduran": "Honduras",
    "Jamaican": "Jamaica",
    "Haitian": "Haiti",
    "Mexican": "Mexico",
    "Panamanian": "Panama",
    "Puerto Rican": "United States of America",
    "Nicaraguan": "Nicaragua",
    "Salvadorean": "El Salvador",
    "Trinidadian": "Trinidad and Tobago",
    "American": "United States of America",
    "Northern Cypriot":'Northern Cyprus'
};



// Maps every country code to a citizenship denomination
export const codes_mapping = {
    "AD": "Andorran",
    "AE": "Emirian",
    "AF": "Afghan",
    "AG": "Antiguan",
    "AI": "Anguillan",
    "AL": "Albanian",
    "AM": "Armenian",
    "AO": "Angolan",
    "AQ": "Antarctic",
    "AR": "Argentinian",
    "WS": "Western Saharan",
    "AT": "Austrian",
    "AU": "Australian",
    "AW": "Arubian",
    "AX": "\u00c5landic",
    "AZ": "Azerbaijani",
    "BA": "Bosnian",
    "BB": "Barbadian",
    "BD": "Bangladeshi",
    "BE": "Belgian",
    "BF": "Burkinabe",
    "BG": "Bulgarian",
    "BH": "Bahrainian",
    "BI": "Burundian",
    "BJ": "Beninese",
    "BL": "Barth\u00e9lemois",
    "BM": "Bermudan",
    "BN": "Bruneian",
    "BO": "Bolivian",
    "VA": NaN,
    "BR": "Brazilian",
    "BS": "Bahameese",
    "BT": "Bhutanese",
    "BW": "Motswana",
    "BY": "Byelorussian",
    "BZ": "Belizean",
    "CA": "Canadian",
    "CC": "Cocossian",
    "CG": "Congolese",
    "CF": "Central African",
    "CH": "Swiss",
    "CI": "Ivorian",
    "CK": "Cook Islander",
    "CL": "Chilean",
    "CM": "Cameroonian",
    "CN": "Chinese",
    "CO": "Colombian",
    "CR": "Costa Rican",
    "CU": "Cuban",
    "CV": "Cape Verdean",
    "CW": "Cura\u00e7aoan",
    "CX": "Christmas Islander",
    "CY": "Cypriot",
    "CZ": "Czech",
    "DE": "German",
    "DJ": "Djiboutian",
    "DK": "Danish",
    "DO": "Dominican",
    "DZ": "Algerian",
    "EC": "Ecuadorian",
    "EE": "Estonian",
    "EG": "Egyptian",
    "EH": "Western Saharan",
    "ER": "Eritrean",
    "ES": "Spanish",
    "ET": "Ethiopian",
    "FI": "Finnish",
    "FJ": "Fijian",
    "FK": "Falkland Islander",
    "FM": "Micronesian",
    "FO": "Faroese",
    "FR": "French",
    "GA": "Gabonese",
    "GB": "British",
    "GD": "Grenadian",
    "GE": "Georgian",
    "GF": "French Guianese",
    "GG": "Guernsey",
    "GH": "Ghanaian",
    "GI": "Gibralterian",
    "GL": "Greenlander",
    "GM": "Gambian",
    "GW": "Guinean",
    "GP": "Guadeloupean",
    "GQ": "Equatorial Guinean",
    "GR": "Greek",
    "GT": "Guatemalan",
    "GU": "Guamanian",
    "GY": "Guyanese",
    "HK": "Hong Konger",
    "HN": "Honduran",
    "HR": "Croatian",
    "HT": "Haitian",
    "HU": "Hungarian",
    "ID": "Indonesian",
    "IE": "Irish",
    "IL": "Israeli",
    "IM": "Manx",
    "IN": "Indian",
    "IQ": "Iraqi",
    "IR": "Iranian",
    "IS": "Icelandic",
    "IT": "Italian",
    "JM": "Jamaican",
    "JO": "Jordanian",
    "JP": "Japanese",
    "KE": "Kenyan",
    "KG": "Kirghiz",
    "KH": "Cambodian",
    "KI": "I-Kiribati",
    "KM": "Comoran",
    "KN": "Kittian",
    "KP": "North Korean",
    "KR": "South Korean",
    "KW": "Kuwaiti",
    "KY": "Caymanian",
    "KZ": "Kazakh",
    "LA": "Laotian",
    "LB": "Lebanese",
    "LC": "Saint Lucian",
    "LI": "Liechtensteiner",
    "LK": "Sri Lankan",
    "LR": "Liberian",
    "LS": "Mosotho",
    "LT": "Lithuanian",
    "LU": "Luxembourgish",
    "LV": "Latvian",
    "LY": "Libyan",
    "MA": "Moroccan",
    "MC": "Monaco",
    "MD": "Moldovan",
    "ME": "Montenegrin",
    "MG": "Malagasy",
    "MH": "Marshallese",
    "MK": "Macedonian",
    "ML": "Malian",
    "MM": "Myanmarese",
    "MN": "Mongolian",
    "MO": "Macanese",
    "MP": "Northern Mariana Islander",
    "MQ": "Martinican",
    "MR": "Mauritanian",
    "MS": "Montserratian",
    "MT": "Maltese",
    "MU": "Mauritian",
    "MV": "Maldivan",
    "MW": "Malawian",
    "MX": "Mexican",
    "MY": "Malaysian",
    "MZ": "Mozambican",
    "NaN": "Namibian",
    "NC": "New Caledonian",
    "NE": "Nigerien",
    "NF": "Norfolk Islander",
    "NG": "Nigerian",
    "NI": "Nicaraguan",
    "NL": "Dutch",
    "NO": "Norwegian",
    "NP": "Nepali",
    "NR": "Nauruan",
    "NU": "Niuean",
    "NZ": "New Zealander",
    "OM": "Omani",
    "PA": "Panamanian",
    "PE": "Peruvian",
    "PF": "French Polynesian",
    "PG": "Papua New Guinean",
    "PH": "Filipino",
    "PK": "Pakistani",
    "PL": "Polish",
    "PM": "Saint-Pierrais",
    "PN": "Pitcairn Islander",
    "PR": "Puerto Rican",
    "PS": "Palestinian",
    "PT": "Portuguese",
    "PW": "Palauan",
    "PY": "Paraguayan",
    "QA": "Qatari",
    "RO": "Romanian",
    "RS": "Serbian",
    "RU": "Russian",
    "RW": "Rwandan",
    "SA": "Saudi Arabian",
    "SB": "Solomon Islander",
    "SC": "Seychellois",
    "SS": "Sudanese",
    "SE": "Swedish",
    "SG": "Singapore",
    "SH": "Saint Helenian",
    "SI": "Slovenian",
    "SK": "Slovak",
    "SL": "Sierra Leonean",
    "SM": "Sanmarinese",
    "SN": "Senegalese",
    "SO": "Somalian",
    "SR": "Surinamer",
    "ST": "S\u00e3o Tomean",
    "SV": "Salvadorean",
    "SY": "Syrian",
    "SZ": "Swazi",
    "TC": "Turks and Caicos Islander",
    "TD": "Chadian",
    "TG": "Togolese",
    "TH": "Thai",
    "TJ": "Tajik",
    "TK": "Tokelauan",
    "TL": "Timorese",
    "TM": "Turkmen",
    "TN": "Tunisian",
    "TO": "Tongan",
    "TR": "Turkish",
    "TT": "Trinidadian",
    "TV": "Tuvaluan",
    "TW": "Taiwanese",
    "TZ": "Tanzanian",
    "UA": "Ukrainian",
    "UG": "Ugandan",
    "US": "American",
    "UY": "Uruguayan",
    "UZ": "Uzbek",
    "VC": "Saint Vincentian",
    "VE": "Venezuelan",
    "VI": "Virgin Islander",
    "VN": "Vietnamese",
    "VU": "Ni-Vanuatu",
    "WF": "Wallisian",
    "YE": "Yemeni",
    "YT": "Mahoran",
    "ZA": "South African",
    "ZM": "Zambian",
    "ZW": "Zimbabwean",
    "KV": "Kosovar",
    "YF": "Serbian",
    "ZR": "Congolese",
    "GN": "Guinean",
    "NA": "Namibian",
    "SD": "Sudanese",
    "GZ": "Israeli",
    "TP": "East Timorian",
    "RY": "Yemeni"
}

// Maps sections to their faculties
const section_map = {
        "Microengineering": "STI",
        "Materials Science and Engineering": "STI",
        "Chemical Engineering and Biotechnology": "STI",
        "Electrical and Electronics Engineering": "STI",
        "Architecture": "ENAC",
        "Computer Science": "IC",
        "Civil Engineering": "ENAC",
        "Communication Systems": "IC",
        "Environmental Sciences and Engineering": "ENAC",
        "Energy Management and Sustainability": "ENAC",
        "Mathematics for teaching": "SB",
        "Financial engineering": "CDM",
        "Physics": "SB",
        "Mathematics": "SB",
        "Computational science and Engineering": "STI",
        "Molecular & Biological Chemistry": "SB",
        "Mechanical Engineering": "STI",
        "Applied Mathematics": "SB",
        "Management": "CDM",
        "Bioengineering": "SV",
        "Life Sciences and Technologies": "SV",
        "Applied Physics": "SB",
        "Chemistry and Chemical Engineering": "SB",
        "Nuclear engineering": "STI",
        "Micro and Nanotechnologies for Integrated Systems": "STI",
        "Passerelle HES": "Other",
        "CMS": "Other",
        "Data Science": "IC",
        "Digital Humanities": "CDH",
        "Chemistry teaching": "SB"
    };

/***********************************************Helper functions***************************************************/

export function add_faculty(x) {
    // add a faculty field to our data by association to each student the faculty to which hw belongs
    
    x['faculty'] = section_map[x['section']]
    return x
}


export function resize() {

    // resizes all divs in our visualization according to the new window height

    redimension(divs, ratios, 'max-height');
    redimension(divs, ratios, 'height');
    redimension(['#slidecontainer'], [10.0 / 762], 'padding-bottom')
    redimension(['#discover_text', '.female_ratio', '.male_ratio'], [10.0 / 762, 5.0 / 762, 5.0 / 762], 'padding-top')
}


export function getRandomInt(min, max) {
    // Get a random integer between min and max
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

export const all_years = [2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]

export function redimension(divs, ratios, attr, unit = 'px', dim = 'h') {
    // redimension a div with the given ratio on the given dimension. the sytle attribute to set (attr) is also given 
    let screen_size;
    if (dim == 'h')
        screen_size = $(window).height()
    else
        screen_size = $(window).width()
    divs.forEach(function(element, index) {
        d3.selectAll(element).style(attr, String(ratios[index] * screen_size) + unit);
        // if(element == '.section_chart' || element == '.timeseries_chart')
        //     console.log(element+' '+String(ratios[index] * screen_size)+unit+' '+dim)
    });
}


export let numberSort = function(a, b) {
    // sorting function
    return a - b;
};

export function round5(x) {
    // rounding function
    return Math.ceil(x);
}


export function format_number(n) {

    // formatting function that keeps only 2 digits
    if (n < 1000)
        return Math.round(n)
    else
        return (parseFloat(n) / 1000).toFixed(1) + 'K'
}

export function dict_inkeys(dict, str) {
    // Function that check if a JSON object "dict" contains a key "str"
    return (str in dict);
}